import Head from 'next/head'
import Navbar from "./Navbar";
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import { useEffect } from 'react';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

const routes = [
    {
        path: '/catchAnimal',
        name: 'Game'
    },
    {
        path: "/testing",
        name: "Testing"
    }
]

const Layout = ({children}: {children: any})=>{
    const router = useRouter();

    useEffect(()=>{
        router.push("/catchAnimal");
    }, [])
    return (
        <>
            <Head>
                <title>UFO Cacther</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar data={routes}/>
            <main className={`${styles.main} ${inter.className}`}>
                {children}
            </main>
            
        </>
    )
}

export default Layout;